version: '3.7'

services:
  app:
    image: nginx:1-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./dist:/opt/project
    ports:
      - "80:80"
    networks:
      - network

networks:
  network: